name: hacksagona-deploy

on:
  #   push:
  #     branches: [ develop_new ]
  #   pull_request:
  #     branches: [ develop_new ]

  workflow_dispatch:

env: # 새로 추가한 부분 
#  S3_BUCKET_NAME: hacksagona-deploy
  PROJECT_NAME: hacksagona-logging

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        shell: bash

      - name: Build with Gradle
        run: ./gradlew build
        shell: bash